### ISSUE TITLE
Error while compressing video

### ISSUE THREAD

**Issue by rakeshteamswork** [rurico/flutter_video_compress#43]
### Description
 java.io.FileNotFoundException: x86/ffmpeg
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:744)
        at android.content.res.AssetManager.open(AssetManager.java:721)
        at nl.bravobit.ffmpeg.FFmpeg.isSupported(FFmpeg.java:65)
        at com.example.flutter_video_compress.FFmpegCommander.compressVideo(FFmpegCommander.kt:25)
        at com.example.flutter_video_compress.FlutterVideoCompressPlugin.onMethodCall(FlutterVideoCompressPlugin.kt:56)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Platform
Android

### Code Example
        final _flutterVideoCompress = FlutterVideoCompress();

       final compressedVideoInfo = await _flutterVideoCompress.compressVideo(
               file.absolute.path,
               quality: VideoQuality.DefaultQuality,
                deleteOrigin: false,
             );

**Comment by rurico** [comment]
Check the specific path, maybe reason for the error of file not found.

**Comment by rakeshteamswork** [comment]
I debugged the code and found that file path is available. But the path returned by ImagePcker.pickVideo is of cache directory and not the original path of video file. I have to look into more details for Image picker module.   
Thanks @rurico
