### ISSUE TITLE
[Bug] App crash in while compression video

### ISSUE THREAD

**Issue by rakeshparveen5** [rurico/flutter_video_compress#45]
### Platform
Android

### Backtracking step (if has)
  1. open application
  2. Select video to compress and exit the app.
  3. Reopen app the app from device launcher
  4. After few seconds app will crash

### Crash report uploaded to Firebase Crashlytics :- 

    Fatal Exception: java.lang.NumberFormatException: null
           at java.lang.Long.parseLong + 557(Long.java:557)
           at java.lang.Long.parseLong + 636(Long.java:636)
           at com.example.flutter_video_compress.Utility.getMediaInfoJson + 45(Utility.kt:45)
           at com.example.flutter_video_compress.FFmpegCommander$compressVideo$1.onFinish + 83(FFmpegCommander.kt:83)
           at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.onPostExecute + 77(FFcommandExecuteAsyncTask.java:77)
           at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.onPostExecute + 12(FFcommandExecuteAsyncTask.java:12)
           at android.os.AsyncTask.finish + 695(AsyncTask.java:695)
           at android.os.AsyncTask.access$600 + 180(AsyncTask.java:180)
           at android.os.AsyncTask$InternalHandler.handleMessage + 712(AsyncTask.java:712)
           at android.os.Handler.dispatchMessage + 106(Handler.java:106)
           at android.os.Looper.loop + 193(Looper.java:193)
           at android.app.ActivityThread.main + 6669(ActivityThread.java:6669)
           at java.lang.reflect.Method.invoke(Method.java)
           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
           at com.android.internal.os.ZygoteInit.main + 858(ZygoteInit.java:858)

**Comment by rakeshparveen5** [comment]
@rurico were you able to reproduce the issue at your end ?

**Comment by TheHemantKaushik** [comment]
Same issue found.

**Comment by sspogra** [comment]
Same issue found.

**Comment by lifenautjoe** [comment]
Same!

**Comment by soile1991** [comment]
Same here

**Comment by rlee1990** [comment]
Having the same issue.

**Comment by omarvbnet** [comment]
Update your flutter and try
Flutter clean 
Flutter run
If pods isn’t install try editing your podfile as the plugin site
And open directory Runner.workspace with xcode 
Clean your project 
Its work for me 👍🏻

**Comment by zhanghuanchong** [comment]
+1

**Comment by pmrajani** [comment]
same issue!

![Screenshot_1](https://user-images.githubusercontent.com/4957175/73588097-d97b6480-44ea-11ea-8886-31f8e7443b29.jpg)

**Comment by biklas7** [comment]
Same crash here :cry:

**Comment by liuhong1happy** [comment]
+1

**Comment by joseluz** [comment]
Same here. 
+1

**Comment by rignaneseleo** [comment]
Same issue. Any workaround?

**Comment by redvg** [comment]
same here.  solved by adding null check to MediaMetadataRetriever.METADATA_KEY_DURATION , MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH and MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT

<img width="1195" alt="2" src="https://user-images.githubusercontent.com/38582053/83715657-3f5d3180-a62e-11ea-8705-643be91c6cec.png">

**Comment by rignaneseleo** [comment]
@redvg your screenshot change is made in /example/ folder. Was it intentional?
Can you make a pull request for this change?

**Comment by duongtruong12** [comment]
the problem because of nl.bravobit:android-ffmpeg hopefully they changed library to com.arthenica:mobile-ffmpeg-full

**Comment by rignaneseleo** [comment]
@duongtruong12 can you fork and pull the fix?

**Comment by sanrixue** [comment]
目前解决了吗

**Comment by sanrixue** [comment]
Process: com.senkoo.apptechnician, PID: 24454
    java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:81)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:165)
        at com.example.flutter_video_compress.Utility.getMediaInfoJson(Utility.kt:38)
        at com.example.flutter_video_compress.FFmpegCommander$compressVideo$1.onFinish(FFmpegCommander.kt:83)
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.onPostExecute(FFcommandExecuteAsyncTask.java:77)
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.onPostExecute(FFcommandExecuteAsyncTask.java:12)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
2020-06-30 10:25:49.863 24454-24454/com.senkoo.apptechnician E/CrashReport: java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:81)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:165)
        at com.example.flutter_video_compress.Utility.getMediaInfoJson(Utility.kt:38)
        at com.example.flutter_video_compress.FFmpegCommander$compressVideo$1.onFinish(FFmpegCommander.kt:83)
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.onPostExecute(FFcommandExecuteAsyncTask.java:77)
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.onPostExecute(FFcommandExecuteAsyncTask.java:12)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by pacifire** [comment]
Facing the same issue.

**Comment by venky9885** [comment]
Same issue here facing app crashing

**Comment by neelansh-creatorstack** [comment]
Same issue
