### ISSUE TITLE
Compatibility with android 10 (api level 29)

### ISSUE THREAD

**Issue by akshaybenk** [rurico/flutter_video_compress#85]
This library crashes if targetsdk version is set to 29, It would be helpful if it was compatible with latest OS as well

Platform
Android

Crash report
``` 
E/FFmpeg  (14502): java.io.IOException: Cannot run program "/data/user/0/com.example.app/files/ffmpeg": error=13, Permission denied
E/FFmpeg  (14502): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
E/FFmpeg  (14502): 	at nl.bravobit.ffmpeg.ShellCommand.run(ShellCommand.java:15)
E/FFmpeg  (14502): 	at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:43)
E/FFmpeg  (14502): 	at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:12)
E/FFmpeg  (14502): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/FFmpeg  (14502): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FFmpeg  (14502): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FFmpeg  (14502): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FFmpeg  (14502): 	at java.lang.Thread.run(Thread.java:919)
E/FFmpeg  (14502): Caused by: java.io.IOException: error=13, Permission denied
E/FFmpeg  (14502): 	at java.lang.UNIXProcess.forkAndExec(Native Method)
E/FFmpeg  (14502): 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
E/FFmpeg  (14502): 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
E/FFmpeg  (14502): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
E/FFmpeg  (14502): 	... 8 more
D/AndroidRuntime(14502): Shutting down VM
E/AndroidRuntime(14502): FATAL EXCEPTION: main
E/AndroidRuntime(14502): Process: com.example.app, PID: 14502
E/AndroidRuntime(14502): java.lang.IllegalArgumentException
E/AndroidRuntime(14502): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:77)
E/AndroidRuntime(14502): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:163)
E/AndroidRuntime(14502): 	at com.example.flutter_video_compress.Utility.getMediaInfoJson(Utility.kt:38)
E/AndroidRuntime(14502): 	at com.example.flutter_video_compress.FFmpegCommander$compressVideo$1.onFinish(FFmpegCommander.kt:83)
E/AndroidRuntime(14502): 	at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.onPostExecute(FFcommandExecuteAsyncTask.java:77)
E/AndroidRuntime(14502): 	at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.onPostExecute(FFcommandExecuteAsyncTask.java:12)
E/AndroidRuntime(14502): 	at android.os.AsyncTask.finish(AsyncTask.java:755)
E/AndroidRuntime(14502): 	at android.os.AsyncTask.access$900(AsyncTask.java:192)
E/AndroidRuntime(14502): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
E/AndroidRuntime(14502): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(14502): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(14502): 	at android.app.ActivityThread.main(ActivityThread.java:7403)
E/AndroidRuntime(14502): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14502): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(14502): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by redvg** [comment]
facing the same. https://github.com/rurico/flutter_video_compress/issues/45

**Comment by duongtruong12** [comment]
did anyone fixed it?

**Comment by jnegii** [comment]
Any fix?

**Comment by marianoarga** [comment]
Nope
